const fs = require('fs'); const path = require('path'); const { extractJson } = require('./schemas');
const dir = __dirname; const cfg = JSON.parse(fs.readFileSync(path.join(dir, 'openrouter.config.json'))); const ocfg = JSON.parse(fs.readFileSync(path.join(dir, 'opencode.config.json'))); const providers = JSON.parse(fs.readFileSync(path.join(dir, 'providers.config.json'))); let cache = { at: 0, data: null };
const enabled = (id) => { const p = providers.providers.find((x) => x.id === id); return p && p.enabled !== false; };
async function eligibleModels() { if (cache.data && Date.now() - cache.at < 3600000) return cache.data; const r = await fetch(`${cfg.baseUrl}/models`, { signal: AbortSignal.timeout(8000) }); if (!r.ok) throw new Error(`catálogo OpenRouter HTTP ${r.status}`); const d = await r.json(); cache = { at: Date.now(), data: d.data || [] }; return cache.data; }
function isFreeHigh(m) { return m && m.id?.endsWith(':free') && m.pricing?.prompt === '0' && m.pricing?.completion === '0' && m.reasoning?.supported_efforts?.includes('high'); }
async function callOpenRouter(messages) { if (!process.env[cfg.apiKeyEnv] || !enabled('openrouter')) throw new Error('OpenRouter não configurado'); const catalog = await eligibleModels(); const models = cfg.models.filter((id) => isFreeHigh(catalog.find((m) => m.id === id))); if (!models.length) throw new Error('nenhum modelo OpenRouter gratuito com HIGH elegível'); const r = await fetch(`${cfg.baseUrl}/chat/completions`, { method: 'POST', signal: AbortSignal.timeout(cfg.timeoutMs), headers: { Authorization: `Bearer ${process.env[cfg.apiKeyEnv]}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ models, messages, reasoning: cfg.reasoning, provider: cfg.provider, max_tokens: cfg.max_tokens }) }); if (!r.ok) throw new Error(`OpenRouter HTTP ${r.status}`); const d = await r.json(); const content = d.choices?.[0]?.message?.content; if (!content) throw new Error('resposta OpenRouter sem conteúdo'); return { content, provider: 'openrouter', model: d.model || models[0] }; }
async function callOpenCode(messages) { if (!process.env[ocfg.apiKeyEnv] || !enabled('opencode')) throw new Error('OpenCode desabilitado ou não configurado'); const r = await fetch(`${ocfg.baseUrl}${ocfg.endpoint}`, { method: 'POST', signal: AbortSignal.timeout(ocfg.timeoutMs), headers: { Authorization: `Bearer ${process.env[ocfg.apiKeyEnv]}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: ocfg.models[0], input: messages, reasoning: ocfg.reasoning, max_output_tokens: ocfg.max_output_tokens, store: false }) }); if (!r.ok) throw new Error(`OpenCode HTTP ${r.status}`); const d = await r.json(); const content = (d.output || []).filter((x) => x.type === 'message').flatMap((x) => x.content || []).filter((x) => x.type === 'output_text').map((x) => x.text).join(''); if (!content) throw new Error('resposta OpenCode sem conteúdo'); return { content, provider: 'opencode', model: d.model || ocfg.models[0] }; }
async function callWithFallback(messages) { try { return await callOpenRouter(messages); } catch (first) { if (enabled('opencode')) { try { return await callOpenCode(messages); } catch (second) { second.cause = first; } } const err = new Error('provedores de IA indisponíveis'); err.cause = first; throw err; } }
module.exports = { callWithFallback, callOpenRouter, callOpenCode, eligibleModels, isFreeHigh, extractJson };
